export { default as Navbar } from './Navbar/newNavbar';
export { default as Searchbar } from './Search/search';
export { default as BrandBar } from './Brand/brand';
export { default as TabContact } from './Tabs/tab1';
export { default as TabLegalNotice } from './Tabs/yasal_uyari_tabpane';
export { default as Footer } from './Footer/newFooter';
export { default as Hakkimizda } from './Tabs/hakkimizda';
export { default as Pazarpolitik } from './Tabs/pazarpol';
export { default as Kariyer } from './Tabs/kariyer';
